import { WorkflowDefinition, WorkflowExecution } from '@/types/workflow';

export const workflowDefinitions: WorkflowDefinition[] = [
  {
    id: 'workflow-1',
    name: 'Webinar Follow-up',
    description: 'Automatically follow up with webinar attendees who haven\'t engaged with support',
    category: 'lead-management',
    triggerType: 'event',
    enabled: true,
    lastRun: new Date(Date.now() - 5 * 60 * 1000),
    nextRun: new Date(Date.now() + 24 * 60 * 60 * 1000),
    totalRuns: 47,
    successRate: 96,
    integrations: ['Zoho CRM', 'Zoho Desk', 'Slack', 'Google Calendar'],
    estimatedDuration: '3-5 min',
  },
  {
    id: 'workflow-2',
    name: 'CRM Data Sync',
    description: 'Synchronize contact data between CRM and support systems',
    category: 'crm',
    triggerType: 'scheduled',
    schedule: 'Every hour',
    enabled: true,
    lastRun: new Date(Date.now() - 2 * 60 * 1000),
    nextRun: new Date(Date.now() + 58 * 60 * 1000),
    totalRuns: 342,
    successRate: 99,
    integrations: ['Zoho CRM', 'Zoho Desk'],
    estimatedDuration: '2-3 min',
  },
  {
    id: 'workflow-3',
    name: 'Support Ticket Assignment',
    description: 'AI-powered ticket routing based on agent expertise and availability',
    category: 'support',
    triggerType: 'event',
    enabled: true,
    lastRun: new Date(Date.now() - 12 * 60 * 1000),
    totalRuns: 1247,
    successRate: 98,
    integrations: ['Zoho Desk', 'Slack'],
    estimatedDuration: '< 1 min',
  },
  {
    id: 'workflow-4',
    name: 'Lead Enrichment',
    description: 'Enrich new leads with company data and engagement scoring',
    category: 'lead-management',
    triggerType: 'event',
    enabled: true,
    lastRun: new Date(Date.now() - 18 * 60 * 1000),
    totalRuns: 584,
    successRate: 94,
    integrations: ['Zoho CRM', 'External APIs', 'Slack'],
    estimatedDuration: '2-4 min',
  },
  {
    id: 'workflow-5',
    name: 'Meeting Scheduler',
    description: 'Smart meeting scheduling with timezone awareness and availability checking',
    category: 'scheduling',
    triggerType: 'manual',
    enabled: true,
    lastRun: new Date(Date.now() - 45 * 60 * 1000),
    totalRuns: 156,
    successRate: 97,
    integrations: ['Google Calendar', 'Zoho CRM', 'Slack'],
    estimatedDuration: '1-2 min',
  },
  {
    id: 'workflow-6',
    name: 'SLA Breach Prevention',
    description: 'Proactively escalate tickets approaching SLA deadlines',
    category: 'support',
    triggerType: 'scheduled',
    schedule: 'Every 15 minutes',
    enabled: true,
    lastRun: new Date(Date.now() - 8 * 60 * 1000),
    nextRun: new Date(Date.now() + 7 * 60 * 1000),
    totalRuns: 2847,
    successRate: 99,
    integrations: ['Zoho Desk', 'Slack', 'Zoho CRM'],
    estimatedDuration: '< 1 min',
  },
  {
    id: 'workflow-7',
    name: 'Account Health Check',
    description: 'Weekly analysis of account engagement and health scoring',
    category: 'monitoring',
    triggerType: 'scheduled',
    schedule: 'Weekly (Monday 9 AM)',
    enabled: true,
    lastRun: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    nextRun: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    totalRuns: 23,
    successRate: 100,
    integrations: ['Zoho CRM', 'Zoho Desk', 'Slack', 'Google Calendar'],
    estimatedDuration: '5-8 min',
  },
  {
    id: 'workflow-8',
    name: 'Onboarding Automation',
    description: 'Complete customer onboarding workflow from signup to first success',
    category: 'communication',
    triggerType: 'event',
    enabled: true,
    lastRun: new Date(Date.now() - 4 * 60 * 60 * 1000),
    totalRuns: 89,
    successRate: 96,
    integrations: ['Zoho CRM', 'Zoho Desk', 'Email', 'Slack', 'Google Calendar'],
    estimatedDuration: '4-6 min',
  },
];

export const workflowExecutions: WorkflowExecution[] = [
  {
    id: 'exec-1',
    workflowId: 'workflow-1',
    workflowName: 'Webinar Follow-up',
    status: 'completed',
    triggerType: 'event',
    startTime: new Date(Date.now() - 5 * 60 * 1000),
    endTime: new Date(Date.now() - 1 * 60 * 1000),
    duration: '4m 12s',
    integrations: ['Zoho CRM', 'Zoho Desk', 'Slack', 'Google Calendar'],
    triggeredBy: 'Webinar: Product Demo Session',
    steps: [
      {
        number: 1,
        title: 'Found Webinar Leads from CRM (Excluding Converted)',
        status: 'success',
        duration: '45s',
        items: [
          { text: 'Luiz Gamo', email: 'luiz.gamo@navanalanda.in', company: 'Example Corp', manager: 'Adam Smith' },
          { text: 'Christopher Karloz', email: 'chris@navanalanda.in', company: 'ABC Corp', manager: 'Adam Smith' },
          { text: 'Amelia Burrows', email: 'amelia.burrows@navanalanda.in', company: 'Zylker Corp', manager: 'Adam Smith' },
        ],
      },
      {
        number: 2,
        title: 'Checked Support Status in Zoho Desk',
        status: 'success',
        duration: '1m 20s',
        items: [
          { text: 'Luiz Gamo: Has support contact record (responded to support)', status: 'success' },
          { text: 'Christopher Karloz: No support contact record (hasn\'t responded)', status: 'error' },
          { text: 'Amelia Burrows: No support contact record (hasn\'t responded)', status: 'error' },
        ],
      },
      {
        number: 3,
        title: 'Scheduled Follow-up Meetings (Only for those who haven\'t responded to support)',
        status: 'success',
        duration: '1m 35s',
        items: [
          { text: '10:00 AM IST Monday, July 14th - Christopher Karloz (ABC Corp)', status: 'info' },
          { text: '10:00 AM IST - Amelia Burrows (Zylker Corp)', status: 'info' },
        ],
      },
      {
        number: 4,
        title: 'Notified Account Manager',
        status: 'success',
        duration: '32s',
        items: [
          { text: 'Sent detailed Slack message to Adam Smith from your account (Thomas Langdom)', status: 'success' },
          { text: 'Included: The 2 scheduled meetings with IST timings', status: 'success' },
          { text: 'Which lead didn\'t need follow-up (Luiz who already responded to support)', status: 'success' },
        ],
      },
    ],
  },
  {
    id: 'exec-2',
    workflowId: 'workflow-2',
    workflowName: 'CRM Data Sync',
    status: 'running',
    triggerType: 'scheduled',
    startTime: new Date(Date.now() - 2 * 60 * 1000),
    integrations: ['Zoho CRM', 'Zoho Desk'],
    steps: [
      {
        number: 1,
        title: 'Fetching New Contacts from CRM',
        status: 'success',
        items: [
          { text: 'Retrieved 47 new contacts from last hour', status: 'success' },
          { text: 'Filtered out 5 duplicates', status: 'info' },
        ],
      },
      {
        number: 2,
        title: 'Enriching Contact Data',
        status: 'running',
        items: [
          { text: 'Enriching 42 contacts with company data...', status: 'info' },
          { text: 'Progress: 28/42 completed', status: 'info' },
        ],
      },
      {
        number: 3,
        title: 'Updating Zoho Desk Records',
        status: 'pending',
        items: [
          { text: 'Waiting for enrichment to complete...', status: 'pending' },
        ],
      },
    ],
  },
  {
    id: 'exec-3',
    workflowId: 'workflow-3',
    workflowName: 'Support Ticket Assignment',
    status: 'completed',
    triggerType: 'event',
    startTime: new Date(Date.now() - 12 * 60 * 1000),
    endTime: new Date(Date.now() - 11 * 60 * 1000),
    duration: '42s',
    integrations: ['Zoho Desk', 'Slack'],
    triggeredBy: 'New Ticket #TKT-4892',
    steps: [
      {
        number: 1,
        title: 'Analyzed Ticket Content',
        status: 'success',
        items: [
          { text: 'Category: Technical Issue - API Integration', status: 'info' },
          { text: 'Priority: High', status: 'error' },
          { text: 'Complexity Score: 7/10', status: 'info' },
        ],
      },
      {
        number: 2,
        title: 'Matched Agent Expertise',
        status: 'success',
        items: [
          { text: 'Sarah Chen - API Integration Expert (Match: 95%)', status: 'success' },
          { text: 'Current workload: 4 active tickets', status: 'info' },
          { text: 'Available: Yes', status: 'success' },
        ],
      },
      {
        number: 3,
        title: 'Assigned and Notified',
        status: 'success',
        items: [
          { text: 'Ticket assigned to Sarah Chen', status: 'success' },
          { text: 'Slack notification sent', status: 'success' },
          { text: 'CRM updated with support interaction', status: 'success' },
        ],
      },
    ],
  },
  {
    id: 'exec-4',
    workflowId: 'workflow-4',
    workflowName: 'Lead Enrichment',
    status: 'failed',
    triggerType: 'event',
    startTime: new Date(Date.now() - 18 * 60 * 1000),
    endTime: new Date(Date.now() - 17 * 60 * 1000),
    duration: '1m 8s',
    integrations: ['Zoho CRM', 'External APIs', 'Slack'],
    triggeredBy: 'New Lead: Tech Innovations Inc',
    steps: [
      {
        number: 1,
        title: 'Retrieved Lead Information',
        status: 'success',
        items: [
          { text: 'Lead: Tech Innovations Inc', status: 'success' },
          { text: 'Contact: Michael Roberts (CTO)', status: 'info' },
          { text: 'Email: m.roberts@techinnovations.com', status: 'info' },
        ],
      },
      {
        number: 2,
        title: 'Enriching Company Data',
        status: 'error',
        items: [
          { text: 'External API timeout after 30s', status: 'error' },
          { text: 'Failed to retrieve company size and revenue data', status: 'error' },
        ],
      },
      {
        number: 3,
        title: 'Fallback: Manual Review Required',
        status: 'info',
        items: [
          { text: 'Created task for sales team to manually enrich', status: 'info' },
          { text: 'Slack notification sent to sales channel', status: 'success' },
        ],
      },
    ],
  },
];
